### ISSUE TITLE
User can view images

### ISSUE THREAD

**Issue by marleydoughty** [marleydoughty/thinking-about-cats#1]
## ⚙️ Feature

Users can browse images of cats

## 📐 Functionality

Create a responsive form that allows users to interact with images on the feed, including commenting on and saving images
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-11-09 at 11 21 09 AM](https://user-images.githubusercontent.com/90815506/140990544-eb050b93-a334-4fc7-ba93-af3fa90c5ae7.png)

![Screen Shot 2021-11-09 at 11 20 45 AM](https://user-images.githubusercontent.com/90815506/140990562-df512cc0-3a5a-49fb-bea9-5234097f9bc2.png)

## ✅ Task List
- [x] Add a `div[class="images"]` to the HTML
- [x] Define a function that makes a  XMLHttp request for images upon load
- [x]  Check that the images look good on both mobile and desktop screens.
- [x] Define a function that takes a single image object and returns a DOM tree that matches one of the example images in the HTML.
- [x] Use a loop to create a DOM tree for each image in the data model and append it to the page when the 'DOMContentLoaded' event is fired.
- [x] Update the value of the `src` attribute to match those received from request
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
