### ISSUE TITLE
User can comment on an image

### ISSUE THREAD

**Issue by marleydoughty** [marleydoughty/thinking-about-cats#2]
## ⚙️ Feature

User can leave a comment on an image in the gallery
## 📐 Functionality

Create a responsive form that allows users to store a comment about a specific image.

## 🖼️ Wireframes

![Screen Shot 2021-11-09 at 11 38 02 AM](https://user-images.githubusercontent.com/90815506/140993285-9c507358-446b-4da9-93af-be848008442d.png)
![Screen Shot 2021-11-09 at 11 41 44 AM](https://user-images.githubusercontent.com/90815506/140993444-3153fc87-bb46-4457-a7bd-c72b653b4763.png)
![Screen Shot 2021-11-09 at 11 38 33 AM](https://user-images.githubusercontent.com/90815506/140993478-6fa16d36-4511-4fe9-9bec-c15e0959cea8.png)

## ✅ Task List

- [x] Add a button that holds the `comment icon`
- [x] Add a form for creating a comment on an image
- [x] Listen for click events on the `comment icon`
- [x] Listen for `input` events on the comment section
- [x] Listen for click events on the `save` button  
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
