### ISSUE TITLE
User can edit a comment 

### ISSUE THREAD

**Issue by marleydoughty** [marleydoughty/thinking-about-cats#3]
## ⚙️ Feature
User can edit a comment
## 📐 Functionality
Allow users to select an existing comment to edit and pre-populate its information into the comment input

## 🖼️ Wireframes

![Screen Shot 2021-11-09 at 12 34 28 PM](https://user-images.githubusercontent.com/90815506/141000456-1dc0979b-17eb-4aa6-951c-deaea7d44f63.png)

![Screen Shot 2021-11-09 at 12 34 50 PM](https://user-images.githubusercontent.com/90815506/141000478-22a029db-b0f3-4987-a4ad-ad35fb3c8f1a.png)

## ✅ Task List

- [x] Ensure that each rendered image is given a data-image-id attribute indicating which image it is.
- [x] Listen for clicks on the parent element of all rendered images.
- [x] Show the comment input if a comment icon was clicked.
- [x] Find the matching entry object in the data model and assign it to the data model's editing property if a comment icon was clicked.
- [x]  Pre-populate the comment input with the input values from the object found in the data model.
- [x]  Update the entry form's submit handler function to conditionally add a new entry object or update the existing one.
- [x]  Update the entry form's submit handler function to conditionally add a new entry DOM tree or replace the existing one.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
