### ISSUE TITLE
User can delete a comment

### ISSUE THREAD

**Issue by marleydoughty** [marleydoughty/thinking-about-cats#4]
## ⚙️ Feature
User can delete a comment 

## 📐 Functionality
Allow users to delete a comment on its edit screen.

## 🖼️ Wireframes

![Screen Shot 2021-11-09 at 12 38 03 PM](https://user-images.githubusercontent.com/90815506/141000880-ff5a5f3a-53b3-464b-8ca9-a2f8bd4a458e.png)

![Screen Shot 2021-11-09 at 12 38 16 PM](https://user-images.githubusercontent.com/90815506/141001021-e3486ca2-8ae2-4e75-81f2-7fc417351b5a.png)

## ✅ Task List
 Show the Entries list if the user clicks Delete.
- [x] Add a click target for deleting a comment on an image that only appears if the user is editing a comment.
- [x]  Remove the comment from the data model and the DOM tree from the page if the user clicks Delete.
- [x]  Show the images page if the user clicks Delete.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
