### ISSUE TITLE
User can favorite an image

### ISSUE THREAD

**Issue by marleydoughty** [marleydoughty/thinking-about-cats#5]
## ⚙️ Feature

Users can favorite an image to be saved in a separate tab and browsed later

## 📐 Functionality

Display the user's favorited images in reverse chronological order so they can see the most recent ones first.

## 🖼️ Wireframes

![Screen Shot 2021-11-16 at 10 39 28 AM](https://user-images.githubusercontent.com/90815506/142045842-5a834a43-f4ca-41d7-aa0a-af1f4ccfe124.png)

![Screen Shot 2021-11-16 at 10 39 40 AM](https://user-images.githubusercontent.com/90815506/142045851-bc2b5d53-bf06-4018-9c4d-985c63e8c1eb.png)

![Screen Shot 2021-11-16 at 10 39 59 AM](https://user-images.githubusercontent.com/90815506/142045864-957b0d4c-ba20-4e7f-83d2-e84d666dc193.png)

## ✅ Task List

- [x] Update image rendering function to include a heart icon for each rendered image
- [x]  Listen for clicks on the parent element of all rendered images.
- [x] Define a function that handles favorited images and changes class name to "favorites"
- [x] Verify that favorited images are saved to local storage along with the rest of the data model on page reload.
- [x] Add favorites to the nav bar
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
