### ISSUE TITLE
User can view an information tab

### ISSUE THREAD

**Issue by marleydoughty** [marleydoughty/thinking-about-cats#6]
## ⚙️ Feature

User can view an information tab

## 📐 Functionality

Allows users to view a tab that contains facts about cats 

## 🖼️ Wireframes

![Screen Shot 2021-11-09 at 1 02 04 PM](https://user-images.githubusercontent.com/90815506/141004081-1cebbf4b-9b81-4f2a-928a-110372428f9b.png)

![Screen Shot 2021-11-09 at 1 01 14 PM](https://user-images.githubusercontent.com/90815506/141003997-b33010ca-9f74-43b0-99f6-6220d104bf60.png)

## ✅ Task List

- [x] Define a function that makes a XMLHttp request for facts upon load
- [x] Add info to the nav bar
- [x] Define a function that takes a single fact object and returns a DOM tree that matches one of the example facts in the HTML.
- [x] Use a loop to create a DOM tree for each fact in the data model and append it to the page when the 'DOMContentLoaded' event is fired.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
